apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-webapp
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-webapp
  template:
    metadata:
      labels:
        app: orders-webapp
    spec:
      containers:
        - name: orders-webapp
          image: lucasfogliarini/orders-webapp:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.4"
              memory: "0.5Gi"
            limits:
              cpu: "0.8"
              memory: "1Gi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: ORDERS_API_URL
              value: "http://orders-webapi"
            - name: KEYCLOAK_URL
              value: "https://keycloak.commerceflow"
