apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders-webapp
  namespace: commerceflow
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - commerceflow.com
      secretName: commerceflow-ingress-tls
  rules:
    - host: commerceflow.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orders-webapp
                port:
                  number: 80
