apiVersion: v1
kind: Secret
metadata:
  name: commerceflow-secrets
  namespace: commerceflow
type: Opaque
stringData:
  ConnectionStrings__CommerceFlowDb: "Host=postgres;Port=5432;Database=commerceflow;User Id=commerceflow;Password=commerceflow!123;Ssl Mode=Disable;Timeout=30;"
  ConnectionStrings__RabbitMQServer: "amqp://commerceflow:commerceflow!123@rabbitmq:5672"
  JwtConfiguration__Audience: "commerceflow-api"  
  JwtConfiguration__Authority: "http://keycloak.commerceflow/realms/commerceflow"
  ORDERS_API_URL: "http://orders.commerceflow"
  SHIPMENTS_API_URL: "http://shipments.commerceflow"
  CorsConfiguration__AllowedOrigins__0: "http://localhost:2003"
  CorsConfiguration__AllowedOrigins__1: "http://localhost:2002"
