apiVersion: v1
kind: Secret
metadata:
  name: commerceflow-ingress-tls
  namespace: commerceflow
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDijCCAnKgAwIBAgIQLK6VWsdHXptMWXW0X3ZlpTANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQD
    DBVrZXljbG9hay5jb21tZXJjZWZsb3cwHhcNMjYwNzIxMTQyOTU5WhcNMjgwNzIxMTQzOTU4WjAg
    MR4wHAYDVQQDDBVrZXljbG9hay5jb21tZXJjZWZsb3cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDGpCnUOL7TApeWeSwe8b/i0ekNgkfMEkf9zRL9717soX4hxul5McZw1MKGsrIb+8E1
    GDdgqROTSf0Q4QTUE1jFBPxQMtR1UU+XgFGKU5o9QcpcDXn820o6/bJ5BqKyy+UWlFC3vKLkdIQd
    cjshRuqc8SHKRqIhuPwAnk4fL9+i+tD2IvSujJq+6DaGM2nZqbSQBEGC4xF/jnIJ2zyEgsLZ4tK4
    1ZOWSPrXidj19NY4hyMlUuql8XuMWZO8fE1VPJdZXhT/nICU4c3shVLT+CDoAyMHpBI6PHLtrtUn
    TZQfoUw4EPYzDeWdOenYTaDb4eMGb54wyuh+4JeGKMSqUpKRAgMBAAGjgb8wgbwwDgYDVR0PAQH/
    BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATBsBgNVHREEZTBjghVrZXljbG9h
    ay5jb21tZXJjZWZsb3eCEGNvbW1lcmNlZmxvdy5jb22CE29yZGVycy5jb21tZXJjZWZsb3eCFnNo
    aXBtZW50cy5jb21tZXJjZWZsb3eCC3JvdXRlLnB1bHNlMB0GA1UdDgQWBBQkXJxxeoEaAu3y9gu2
    teG2E75zRTANBgkqhkiG9w0BAQsFAAOCAQEAHG4eAH8WRq2EGTUDorAfLqMkBJ0qC6VBL3j+KYdq
    kf+Jb0j0GXXuVRKSjjxwRfR3k9dlxzZ6Onl3WIaCcqOmvuKWsLH9flD8Fs1bFAQLemW2lZNp5pRQ
    F6ZwaEoHYvle8m4jmiBfNYuOGiAsbeDMXUzr5p/3OFU9SYMODvV3iEeVqr7mGk0f/2elFkoyvNVR
    FIxP6bJ8ixD+bS4Tv6g/YTgk0iADMgqCe+vuAMIIncR4SRdL7HAa+jm4Ww5kxca2OhtR02erfsWh
    0B4D+8OiX8GGOMC9epp24PD2rzAhs1whtDx7Beu1JaHYQh3zQ74dKM3LXNjCJyfxp4jdnM69kA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAxqQp1Di+0wKXlnksHvG/4tHpDYJHzBJH/c0S/e9e7KF+IcbpeTHGcNTChrKy
    G/vBNRg3YKkTk0n9EOEE1BNYxQT8UDLUdVFPl4BRilOaPUHKXA15/NtKOv2yeQaissvlFpRQt7yi
    5HSEHXI7IUbqnPEhykaiIbj8AJ5OHy/fovrQ9iL0royavug2hjNp2am0kARBguMRf45yCds8hILC
    2eLSuNWTlkj614nY9fTWOIcjJVLqpfF7jFmTvHxNVTyXWV4U/5yAlOHN7IVS0/gg6AMjB6QSOjxy
    7a7VJ02UH6FMOBD2Mw3lnTnp2E2g2+HjBm+eMMrofuCXhijEqlKSkQIDAQABAoIBAQCvuJOEODqe
    wcFFjKW6LhOYXCb1G1XWMinbXCm716A6ZlYFHUh2PNEWCTCYJcYnuRrelDCQ4qD9f8tNvjEeRosV
    puZpL74AllB5bjszyec831FbA1TxmS/eZYUXSQZucq6Svdt13nqe7G/e+KlUM77h3PIOVVOhz1mm
    VmQ3dIs6SWSCpyhbgDBSYOQMJZ3KR2kqeMayig1toL+1NdkyrO2A7AZubsrir4L3T+HGgAjgwVqk
    P5kJiO5PF2g6bGsn1EkFbblcEGlHoq+Gjv34WsW3HTpIlPf1ARpPidQ8OPhNYbOA4gC9N0Z65hft
    y3LUNm0S5UXkDxbYd8/IXLCHdNu9AoGBANAR+r8XWBYBEDQaDr79ak8yogM+3ZuHPhcfivFFjFKE
    OF+nRq15Lnu5CbOXae3E8LyTPYPSjLliBdYWiqswOnOs1A64UGuri7F/PM1lSRIDC6P/pFuAuNAe
    qgv0p+sd3TznmCcMvXFbw8Ml8gxPI0kp3L3pytgEIXr9sKKjReL/AoGBAPRmJvfubi8TFn59doxH
    FsUDgcZkMxoClYIENrLhSZpuHPpUA3DiN+t9bOtt5HToK3EhXPGKNByGDRw/FhGznaFDFssfUqn5
    8ac6k1fFxFQKUKN3S58i2bJOD+R0qS58yGD+SgWqNggtJZQmKYDmxCZ5P/xOhTBwFYntQWV8SNpv
    AoGAI2MLbDiCKKvhn5rW6zCaRgHsf/TPJ8ZmjvQ0Yzha1yXZmJsQcCxt9WjQ95RG1cNq1geMrMDA
    Yj8DkxeeWeMH7eh04FQEiWtRhMyJAL27Ia8W6bturolD5VFxxjrD3D7mA5e3ztxh08exkZ0Af4tu
    CuFtw3bhor+BGjPPOLngBu0CgYBIZ9szqNfL6oPHhbQRax470AYqmJTrJ8jTdBwgcs4zilvbbfh3
    AQ5AHjCerzf3yrDUG2ZFyQQXTz+jFq2bIPOaSx39n5IF+Z62RIxSfKzlmQi65STqSJDmWmoq7MUS
    mLVkxvF3LC5FzdpMQeIZ5kRGgbWLMlgTOaGn8zpkrqWG0QKBgEZeQFAruuxte2xt5H973w8cD32O
    Oun9uS269kPxrGeYmBvqBT5lLKDTijaKvf9ECmvk90ukvzyuMUFpkaT/O9AMucnV7uuQu0Xpv8Ql
    swSqrDqT2z3dxu745m8LgQzd43IdwTE3hMevYMRZ9Lf809spKCteRgjDkJs+noau2jxI
    -----END RSA PRIVATE KEY-----
