apiVersion: v1
kind: Secret
metadata:
  name: commerceflow-secrets
  namespace: commerceflow
type: Opaque
stringData:
  ConnectionStrings__CommerceFlowDb: "Host=postgres;Port=5432;Database=commerceflow;User Id=commerceflow;Password=commerceflow!123;Ssl Mode=Disable;Timeout=30;"
  ConnectionStrings__RabbitMQServer: "amqp://commerceflow:commerceflow!123@rabbitmq:5672"
  JwtConfiguration__Audience: "commerceflow-api"  
  JwtConfiguration__Authority: "https://keycloak.commerceflow/realms/commerceflow"
