apiVersion: v1
kind: Secret
metadata:
  name: commerceflow-secrets
  namespace: commerceflow
type: Opaque
stringData:
  ConnectionStrings__CommerceFlow: "Host=postgres;Port=5432;Database=commerceflow;User Id=commerceflow;Password=commerceflow!123;Ssl Mode=Disable;Timeout=30;"
  ConnectionStrings__KafkaServer: "kafka:9092"
