apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-eventworkers
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-eventworkers
  template:
    metadata:
      labels:
        app: shipments-eventworkers
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube # Garante que o Pod seja agendado no n� espec�fico
      containers:
        - name: shipments-eventworkers
          image: lucasfogliarini/shipments-eventworkers:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.4"
              memory: "0.5Gi"
            limits:
              cpu: "0.8"
              memory: "1Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - secretRef:
                name: commerceflow-secrets
