apiVersion: v1
kind: Service
metadata:
  name: shipments-eventworkers
  namespace: commerceflow
spec:
  selector:
    app: shipments-eventworkers
  type: ClusterIP
  ports:
    - port: 2003
      targetPort: 8080