apiVersion: v1
kind: Service
metadata:
  name: commerceflow-ordereventworkers
  namespace: commerceflow
spec:
  selector:
    app: commerceflow-ordereventworkers
  type: ClusterIP
  ports:
    - port: 2002
      targetPort: 8080