apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-webapi
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-webapi
  template:
    metadata:
      labels:
        app: shipments-webapi
    spec:
      containers:
        - name: shipments-webapi
          image: lucasfogliarini/shipments-webapi:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.4"
              memory: "0.5Gi"
            limits:
              cpu: "0.8"
              memory: "1Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: CorsConfiguration__AllowedOrigins__0
              value: "https://route.pulse"
          envFrom:
            - secretRef:
                name: commerceflow-secrets
          livenessProbe: # LivenessProbe verifica se o Pod está vivo e reinicia se necessário
            httpGet:
              path: /health/live
              port: 8080
            failureThreshold: 1 # Reinicia o Pod imediatamente ao detectar falha
          readinessProbe: # ReadinessProbe verifica se o Pod est� pronto para receber tr�fego.
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 20 # Intervalo entre as verifica��es
            timeoutSeconds: 5 # Tempo de espera para a resposta do probe
            failureThreshold: 1 # Pod continua rodando, mas � removido dos endpoints do Service
            successThreshold: 1 # N�mero de sucessos necess�rios para considerar o Pod pronto para tr�fego novamente
            initialDelaySeconds: 2 # Tempo de espera antes de iniciar as verifica��es
