apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipments-webapi
  namespace: commerceflow
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shipments.commerceflow
      secretName: commerceflow-ingress-tls
  rules:
    - host: shipments.commerceflow
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shipments-webapi
                port:
                  number: 80
